### ISSUE TITLE
Same source file for multiple functions (Algolia)

### ISSUE THREAD

**Issue by maticzav** [graphcool/modules#21]
Hi!

I don't truly know if this works or doesn't (in my case it didn't work) and that's why I am writing this feature request or bug report (depends on how you take it).

The idea is to be able to use the same source file (function) in multiple use cases and only vary functions behaviour by changing ENV vars in `graphcool.yml` configuration file.

For example (in Algolia-sync case) you could, instead of multiple files for each index have only one source file `sync.js` and the configuration file would look something like this:
```yml
types: ./types.graphql

functions:
  syncDocuments:
    handler:
      code:
        src: ./src/sync.js
        environment:
          ALGOLIA_APP_ID: ${env:ALGOLIA_APP_ID}
          ALGOLIA_API_KEY: ${env:ALGOLIA_API_KEY}
          ALGOLIA_GRAPHCOOL_TYPE: 'Document'
          ALGOLIA_INDEX_NAME: 'documents'
    type: subscription
    query: ./src/syncDocuments.graphql
  syncRequests:
    handler:
      code:
        src: ./src/sync.js
        environment:
          ALGOLIA_APP_ID: ${env:ALGOLIA_APP_ID}
          ALGOLIA_API_KEY: ${env:ALGOLIA_API_KEY}
          ALGOLIA_GRAPHCOOL_TYPE: 'Request'
          ALGOLIA_INDEX_NAME: 'requests'
    type: subscription
    query: ./src/syncRequests.graphql

rootTokens:
- syncDocuments
- syncRequests
```

Hope it makes sense!

I have already tried to implement it, but the problem occurred with `process.env.ALGOLIA_INDEX_NAME` which had, in` syncRequests` case, value 'documents' instead of 'requests'. From this, I think the problem might be with sharing `environment variables` between functions. Is there any way to fix this or is it meant to work this way?

Thanks in advance!
